spring:
    datasource:
        url: jdbc:mysql://20.169.156.3:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
