spring:
    datasource:
        url: jdbc:mysql://csqdb.mysql.database.azure.com:3306/mydb?serverTimezone=UTC&sslmode=required
        username: myroot
        password: Sq123456
        driver-class-name: com.mysql.cj.jdbc.Driver
